name: Deploy testnet on Digital Ocean

on: workflow_dispatch

env:
  CARGO_INCREMENTAL: '0'
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:
  launch-testnet:
    name: Launch Digital Ocean testnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Rust and required components
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          target: x86_64-unknown-linux-musl
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      - name: Install musl-tools
        run: sudo apt update -y && sudo apt install -y musl-tools
      - name: Build node
        run: cargo build --release --target x86_64-unknown-linux-musl --features="always-joinable"

      - name: Launch testnet
        uses: lionel1704/safe-testnet-action@master
        with:
          do-token: ${{ secrets.DO_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-key-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ssh-secret-key: ${{ secrets.SSH_SECRET_KEY  }}
          node-path: $GITHUB_WORKSPACE/target/x86_64-unknown-linux-musl/release/sn_node
          node-count: 2